---
title: "Lung Cancer Regressions"
author: "Pingyao Liu"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
set.seed(1000)

data <- read.csv("data/lung_cancer_mortality_data_test_v2.csv")
data
```


```{r initialization}
library(tidyverse)
library(ggplot2)
library(gtsummary)
library(dplyr)
library(lme4)
library(psych)
library(lmerTest)
```

```{r}
data <- data %>% mutate(survived = as.factor(survived))
data <- data %>% mutate(gender = case_when(gender == "Female" ~ 1, gender == "Male" ~ 0))
data <- data %>% mutate(family_history = case_when(family_history == "Yes" ~ 1, family_history == "No" ~ 0))
data <- data %>% mutate(gender = as.factor(gender), family_history = as.factor(family_history), survived = as.factor(survived))
data <- data %>% mutate(across(12:15, as.factor))
data %>% head()
```

<!-- ```{r} -->
<!-- exp_vars <- c("age", "gender", "country", "diagnosis_date", "cancer_stage", "beginning_of_treatment_date", "family_history", "smoking_status", "bmi", "cholesterol_level", "hypertension", "asthma", "cirrhosis", "other_cancer", "treatment_type", "end_treatment_date") -->

<!-- lin_reg_fun <- function(dt, var) { -->
<!--   # Fit the linear model -->
<!--   model <- lm(survived ~ var, data = dt) -->

<!--   # Return the summary of the model -->
<!--   return(summary(lm_model)) -->
<!-- } -->

<!-- results <- lapply(exp_vars, function(var) lin_reg_fun(data, exp_vars)) -->
<!-- ?lapply -->
<!-- models -->
<!-- ``` -->

```{r}
#extract independent variables from the training dataset
indep_var <- subset(train, select = -c(id, survived))

#fit univariate regression model for each independent variables
selected_vars_p <- sapply(names(indep_var), function(var) {
  model <- glm(survived ~ train[[var]], family = binomial, data = train)
  summary(model)$coefficients[, "Pr(>|z|)"][2]
})

selected_vars_p

#track variables that meet the pre-specified criteria - e.g., p-value < 0.1
selected_vars <- names(indep_var)[selected_vars_p < 0.1]

selected_vars
```

```{r}
# multivariate analysis 
multivar_model <- glm(survived ~ gender + smoking_status, family = binomial, data = train)

summary(multivar_model)
```

```{r}
# verifying results 
predictions <- predict(multivar_model, newdata = test)

mean((test$survived - predictions)^2)
```

```{r}
# multivariate analysis with all variables 
multivar_model_2 <- glm(survived ~ age + gender + country + cancer_stage + family_history + smoking_status + bmi + cholesterol_level + hypertension + asthma + cirrhosis + other_cancer + treatment_type, family = binomial, data = train)

summary(multivar_model_2)
```

```{r}
# verifying results 
predictions_2 <- predict(multivar_model_2, newdata = test)

mean((test$survived - predictions_2)^2)
```



